# Generated by Django 5.1.6 on 2025-03-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo_lists/'),
        ),
    ]
