# Generated by Django 5.1.6 on 2025-03-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_todolist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='boundary_date',
            new_name='date_of_note',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='note_date',
            new_name='deadline',
        ),
        migrations.AddField(
            model_name='todolist',
            name='body',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
