# Generated by Django 5.1.6 on 2025-03-13 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_boundary_date_todolist_date_of_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date_of_note',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='body',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дедлайн задачи'),
        ),
    ]
