# Generated by Django 5.1.6 on 2025-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_todolist_date_of_note_alter_todolist_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=2),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
