# Generated by Django 5.1.6 on 2025-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_todolist_priority_alter_todolist_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='body',
            field=models.TextField(default='', max_length=512, verbose_name='To-do лист'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo_lists/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
