# Generated by Django 5.1.6 on 2025-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_todolist_body_alter_todolist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotags',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
