# Generated by Django 5.1.6 on 2025-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_todotags_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(to='web.todotags', verbose_name='Теги'),
        ),
    ]
