# Generated by Django 5.1.6 on 2025-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_todolist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.todotags', verbose_name='Теги'),
        ),
    ]
