# Generated by Django 5.1.6 on 2025-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_todolist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.todotags', verbose_name='Теги'),
        ),
    ]
